CREATE TABLE student(
    stud_id INT PRIMARY KEY,
	name VARCHAR(50),
	roll_no INT NOT NULL,
    city VARCHAR(50)
);

INSERT INTO student VALUES(105,'SOURABH',221230061,'GWALIOR');
INSERT INTO student VALUES(108,'RAGHAV',221230051,'UP');
INSERT INTO student VALUES(101,'RISHABH',221230056,'DELHI');
INSERT INTO student VALUES(107,'PRIYANSHU',221230049,'DELHI');

ALTER TABLE student
ADD COLUMN age INT;

ALTER TABLE student
DROP COLUMN age;

ALTER TABLE student
RENAME COLUMN city TO Town;

ALTER TABLE student
RENAME TO users;

SELECT * FROM users;